import{S as d,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const y="46065959-261c5874db82aaa09dfa5c313",m="https://pixabay.com/api/";async function p(n,r=1,s=40){const t=`${m}?key=${y}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;try{const e=await fetch(t);if(!e.ok)throw new Error("Error fetching images");return e.json()}catch(e){throw console.error("Error:",e),e}}let a;function h(n){const r=document.querySelector(".gallery"),s=n.map(t=>`
    <a class="gallery-item" href="${t.largeImageURL}">
      <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </a>
  `).join("");r.innerHTML=s,a?a.refresh():a=new d(".gallery a")}function g(){document.querySelector(".gallery").innerHTML=""}function c(n){l.error({title:"Error",message:n})}function w(){l.info({title:"Loading",message:"Searching for images...",timeout:!1,progressBar:!0})}function b(){l.hide({},document.querySelector(".iziToast-info"))}const u=document.querySelector("#search-form"),L=u.querySelector('input[name="searchQuery"]');document.querySelector(".gallery");let f=1;u.addEventListener("submit",S);async function S(n){n.preventDefault();const r=L.value.trim();if(r===""){c("Please enter a search query");return}g(),f=1,await $(r)}async function $(n){w();try{const r=await p(n,f);if(r.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}h(r.hits),showSuccess(`Found ${r.totalHits} images`)}catch{c("Something went wrong. Please try again later.")}finally{b()}}
//# sourceMappingURL=index.js.map
